<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="/design/default/css/foundation.css">
    <link rel="stylesheet" type="text/css" href="/design/default/css/install.css">
</head>
<body>

<div class="large-4 large-offset-4 columns form">
    <div class="row" style="margin-top:15px;">
        <div class="panel">
            <pre><?php echo json_encode($content, JSON_PRETTY_PRINT); ?></pre>
        </div>
    </div>
</div>
</body>
</html>